### ISSUE TITLE
JavaScript Exception thrown when the chart doesn't have data

### ISSUE THREAD

**Issue by andrewz-skyward** [julianna-langston/chartjs2music#82]
I'm using vue-chartjs and receive an error when the chart doesn't have any data points:
![image](https://github.com/julianna-langston/chartjs2music/assets/33626728/4be0fb47-3b77-4ca1-845e-4cb0fa6edb22)

It looks like a check just needs to be added to ensure data is present (and potentially elsewhere, this is just the first point of failure):
![image](https://github.com/julianna-langston/chartjs2music/assets/33626728/63303aaa-b15e-4f25-bd8b-a974aec362cb)

A workaround could be to only register the chart2Music plugin if the chart has data, but the vue-chartjs only allows global plugin registration and I have multiple charts on my page and any one could potentially be empty.

**Comment by julianna-langston** [comment]
Thank you for opening an issue! I was able to reproduce the problem, and have shipped a fix in v0.1.4. The plugin shouldn't throw any errors anymore when a chart is initialized with data. Please check out the latest version of the library, and let me know if it meets your needs.

One warning - this plugin doesn't currently support *updating* chart.js data. It will ignore any chart that starts with empty data, and continue to ignore the chart, even after data is added. 

If you expect to be regularly updating data in your charts, please let me know, so that I can track interest in that feature.
